# Generated by Django 3.2.3 on 2021-06-15 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_alter_articulo_fecha_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='seccion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion_seccion', to='sitio.seccion'),
            preserve_default=False,
        ),
    ]
